## 前端异常捕获与实践

### 前言

什么是异常？异常就是预料之外的事件，往往影响了程序的正确运行，例如下面几种场景：
 - 页面元素异常(按钮无法点击、元素不展示)
 - 页面卡顿
 - 页面白屏

 这些情况都是极其影响用户体验的。对于前端来说，异常虽然不会导致计算机宕机，但是往往会导致用户的操作被阻塞。

### 异常分类

从根本上来说，异常就是一个数据结构，他存了异常发生时相关信息，譬如错误码，错误信息等。其中message属性是唯一一个能够保证所有浏览器都支持的属性，除此之外，IE、Firefox、Safari、chrome以及Opera都为事件添加了其他相关信息。比如IE添加了与message属性完全相同的description属性，还添加了保存这内部错误数量的number属性。Firefox添加了fileName、lineNumber和stack(包含堆栈属性)，所以，考虑浏览器兼容性，最好还是只使用message属性。


执行JS期间可能会发生的错误有很多类型。每种错误都有对应的错误类型，而当错误方式时就会抛出响应的错误对象。ECMA-262中定义了下列7种错误类型：

 - Error：错误的基类，其他错误都继承自该类型。
 - EvalError：Eval函数执行异常；
 - RangeError：数组越界；
 - ReferenceError：尝试引用一个未被定义的变量时，将会抛出此异常；
 - SyntaxError：语法解析不合理；
 - TypeError：类型错误，用来表示值的类型是非预期类型时发生错误；
 - URIError：以一种错误的方式使用全局URI处理函数而产生的错误；

 ### 异常处理

 ECMA-262 第 3 版中引入了 try-catch 语句，作为 JavaScript 中处理异常的一种标准方式，基本的语法如下所示。这和 Java 中的 try-catch 语句是全完相同的。

```javascript
try {
  // 可能会导致错误的代码
} catch (error) {
  // 在错误发生时怎么处理
}
```

如果`try` 块中的任何代码发生错误，就会立即退出代码执行过程，然后，执行`catc`h块。此时`catch`块会接收到一个包含错误信息的对象。这个对象中包含的信息因浏览器而异。但共同的是有一个保存错误信息的`message`属性。`final`子句在`try-catch`语句中时可选的。但是`final`子句一经使用，其代码无论如何都会执行，换句话说，则无论try或者`catch`语句包含什么代码，甚至是`return`语句都不能阻止`final`语句的执行。

一般的语法错误在编辑器就会体现出来，常表现的错误信息为：`Uncaught SyntaxError: Invalid or unexpected token xxx` 这样。但是这种错误会直接抛出异常，常使程序崩溃，一般在编码时候容易观察得到。

`try-catch`在我们的代码中经常见到，通常给代码块进行`try-catch`包装后，当代码块发生错误时catch将能捕捉到错误信息，页面可以继续执行。但是`try-catch`处理异常的能力有限，***只能捕捉到运行时非异步错误，对于语法错误和异步错误就显得无能为力，捕捉不到 ***。可以使用`onerror`捕获到运行时的同步/异步错误。


### 异常分析

#### JS运行时错误：

JS运行时错误分为**同步错误**与**异步错误**。代码错误一般在开发和测试阶段就能发现，用`try-catch`也能捕获到，但是，`try-catch`只能捕获运行时同步错误，其他类型无法捕获。可以使用`onerror`可以捕获到运行时的同步/异步错误。

#### JS语法错误：

语法错误可以在开发阶段发现，不过凡事总是有例外，线上还是会收到一些语法错误的警告，但多半是JSON解析出错和浏览器兼容性导致。语法错误无法通过`try-catch`捕获。JSON解析出错可以通过`try-catch`捕获。

再看几个例子：

```javascript
JSON.parse('{name:xiaoming}');  // Uncaught SyntaxError: Unexpected token n in JSON at position 1
JSON.parse('{"name":xiaoming}'); // Uncaught SyntaxError: Unexpected token x in JSON at position 8
JSON.parse('{"name":"xiaoming"}');  // 正常
var testFunc () => { }; // 在 IE 下会抛出 SyntaxError，因为 IE 不支持箭头函数，需要通过Babel等工具事先转译下
```
使用 `JSON.parse` 解析时出现异常就是一个很好的使用 try-catch 的场景：

```javascript
try {
  JSON.parse(remoteData); // remoteData 为服务端返回的数据
} catch {
  console.error("服务端数据格式返回异常，无法解析", remoteData);
}
```

并不是捕获到错误就结束了，捕获到错误后，我们需要思考当错误发生时：
 - 错误是否是致命的，会不会导致其它连带错误
 - 后续的代码逻辑还能不能继续执行，用户还能不能继续操作
 - 是不是需要将错误信息反馈给用户，提示用户如何处理该错误
 - 是不是需要将错误上报服务端
对应上面的问题这里就会有很多解决方案了，譬如

1、如果是服务器未知异常导致，可以阻塞用户操作，弹窗提示用户"服务器异常，请稍后重试"。并提供给用户一个刷新的按钮；
```javascript
try {
  return JSON.parse(remoteData);
} catch (error) {
  Modal.fail("服务器异常，请稍后重试");
  return false;
}
```
2、如果是数据异常导致，可阻塞用户操作，弹窗提示用户"服务器异常，请联系客服处理~"，同时将错误信息上报异常服务器，开发人员通过异常堆栈和用户埋点定位问题原因；

```javascript
try {
  return JSON.parse(remoteData);
} catch (error) {
  Modal.fail("服务器异常，请联系客服处理~");
  logger.error("JSON数据解析出现异常", error);
  return false;
}
```
3、如果数据解析出错属于预料之中的情况，也有替代的默认值，那么当解析出错时直接使用默认值也可以；

```javascript
try {
  return JSON.parse(remoteData);
} catch (error) {
  console.error("服务端数据格式返回异常，使用本地缓存数据", erorr);
  return localData;
}
```

***任何错误处理策略中最重要的一个部分，就是确定错误是否致命。***

#### 异步错误：

```javascript
try {
  setTimeout(() => {
    undefined.map(v => v);
  }, 1000)
} catch(e) {
  console.log("捕获到异常：", e);
}
 
Uncaught TypeError: Cannot read property 'map' of undefined
  at <anonymous>:3:15
```

 并没有捕获到异常，`try-catch`对语法和异步错误却无能为力，捕获不到，这是需要特别注意的地方。
异步错误(Promise错误)：需监听`unhandledrejection`来帮忙捕获这部分错误。
 - 静态资源加载异常：
     通过`onerror` 或`addEventListenerer('error')`捕获。
 - ajax请求异常
     如果使用axios库，可以使用axios的拦截器处理

### 异常捕获

#### window.onerror

全局监听捕获JS产生的错误，当JS运行时发生错误，`window`会触发一个`ErrorEvent`接口的`error`事件，并执行`window.onerror()`**同步错误可以捕获到，但是`window.onerror()`无法捕获静态资源异常和JS代码错误。**

```javascript
/**
 * @param {String}  message    错误信息
 * @param {String}  source     出错文件
 * @param {Number}  lineno     行号
 * @param {Number}  colno      列号
 * @param {Object}  error      Error对象（对象）
 */
window.onerror=function(message, source, lineno, colno, error){
  console.log("捕获到异常：",{ message, source, lineno, colno, error });
};
```

#### 静态资源加载异常
  ##### 方法一：onerror捕获
        通过在静态资源标签上加`onerror`方法，捕获静态资源加载异常。
  ##### 缺点：
   - 每个静态资源标签都加上onerror方法，代码侵入性太强。
   - 在单文件应用中，当我们使用script标签引入了JS文件，当该JS文件的来源域名和网页的域名不同时，这时如果该JS文件内部没有报错，则只能捕获到script Error，而不是详细的错误信息，这是由于浏览器的跨域限制。解决办法：
     - 需要在跨域的script标签中加入crossorigin属性，例如<script type="text/javascript" src="example.js" crossorigin></script>
     - 需要给跨域资源的服务器的response header设置允许跨域：Access-Control-Allow-Origin: *
   - 不能全局捕获到非JS脚本资源的加载异常，解决方案：使用window.addEventListener捕获。
   - 无法捕获语法错误。
   - 最好写在所有JS脚本的前面，否则有可能捕获不到错误。

```javascript
<script>
  functionerrorHandler(error){
    console.log("捕获到静态资源加载异常", error);
  }
</script>
<script src="http://cdn.xxx.com/js/test.js" onerror="errorHandler(this)"></script>
<link rel="stylesheet" href="http://cdn.xxx.com/styles/test.css" onerror="errorHandler(this)">
```

##### 方法二：addEventLisstener('error')

当一项资源加载失败，加载资源的元素会触发一个Event接口的error事件，并执行该元素上的onerror()处理函数。这些error事件不会冒泡到window，但能被单一的`window.addEventListener`捕获。
由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断HTTP的状态时404或者500等，需要配合服务端日志排查分析才可以。`window.addEventListener`在运行时的错误和资源加载时的错误对象不同。

##### 缺点：
无法准确判断HTTP状态是什么，需要配合服务端日志排查分析才可以。

```javascript
<!DOCTYPEhtml>
<htmllang="zh">

 <head>
  <metacharset="UTF-8">
  <metaname="viewport"content="width=device-width, initial-scale=1.0">
  <title>error</title>
  <script>
    window.addEventListener('error',(error)=>{
      console.log('捕获到异常：', error);
    },true)
  </script>
 </head>
<body>
  <imgsrc="https://itemcdn.zcycdn.com/15af41ec-e6cb-4478-8fad-1a47402f0f25.png">          </body>
 </html>
```
> 注意：<br/>
> 不同浏览器下返回的error对象可能不同，需要兼容处理。<br/>
> 需要注意避免addEventListener重复监听。

#### Promise异常

Promise中的没有写catch的Promise中抛出的异常不能被`try-catch`和`window.onerror`捕获，这时就需要监听`unhandledrejection`来帮助捕获这部分错误，所以务必要在Promise中不要忘记写catch处理抛出的异常。为了防止有漏掉的Promise异常，建议在全局增加一个对unhandledrejection的监听，用来全局监听`Uncaught Promise Error`。

```javascript
window.addEventListener("unhandledrejection",function(e){
  e.preventDefault();
  console.log("捕获到 promise 错误了");
  console.log("错误的原因是", e.reason);
  console.log("Promise 对象是", e.promise);
  returntrue;
});

Promise.reject("promise error");
newPromise((resolve, reject)=>{
  reject("promise error");
});
newPromise((resolve)=>{
  resolve();
}).then(()=>{
  throw"promise error";
});
```

#### React异常

React处理异常的方式不同。虽然try-catch适用于许多非普通JavaScript应用程序，但他只适应于`命令式代码`。因为React组件是声明性的，所以，`try-catch`不是一个可靠的选项。为了弥补这一点，React实现了所谓的**错误边界(error boundaries)**。错误边界是react16版本之后引入的组件，**它捕获子组件树中的任何地方JavaScript错误，同时还记录错误并显示回退用户界面。**

**缺点：**
错误边界无法捕获以下异常：
 - 事件处理器
 - 异步代码
 - 服务端的渲染代码
 - 在错误边界区域内的错误

 ```javascript
classErrorBoundaryextendsReact.Component{
  constructor(props){
    super(props);
    this.state ={ hasError:false};
  }

  componentDidCatch(error, info){
    // 展示出错的UI
    this.setState({ hasError:true});
    // 将错误信息上报到日志服务器
    logErrorToMyService(error, info);
  }

  render(){
    if(this.state.hasError){
      // 可以展示自定义的错误样式
      return<h1>Something went wrong.</h1>;
    }
    returnthis.props.children;
  }}
 ```

 使用错误边界处理组件：

```javascript
<ErrorBoundary>
  <MyWidget/>
</ErrorBoundary>
```
#### Vue 异常

errorHandler获取组件生命周期钩子里的错误，从2.4.0起这个钩子也会捕获Vue自定义事件处理函数内部的错误。

```javascript
Vue.config.errorHandler=(err, vm, info)=>{
  console.error("通过vue errorHandler捕获的错误");
  console.error(err);
  console.error(vm);
  console.error(info);
};
```

生命周期钩子里错误是可以被errHandler捕获到的，但比如当我们主动点击div触发clickerror时，会发现这时错误并没有被errorHandler捕获到，控制台输出的是`Uncaught Error`，也就是没有被捕获到的错误，所以需要注意的是，errorHandle方法**目前还捕获不到绑定监听事件触发的异常，但是可以捕获到在生命周期钩子中调用的方法的错误。**可以使用**window.onerror**但在MVVM框架中使用onerror监听全局异常会发现并不能捕获到绑定事件的详细错误信息，只会输出`Script Error`，这时可以尝试进入webpack配置，设置`devtool：'source-map'`,这时控制台再次打印可以看见成功捕获到绑定事件的错误。

#### 请求异常

重写XMLHttpRequest对象的方法或以最常用的HTTP请求库axios为例，使用axios的拦截器统一处理异常。

##### 重写XMLHttpRequest对象

```javascript
function(){
        var_self=this;

        // 重写 open
        XMLHttpRequest.prototype.open=function(){
            // 先在此处取得请求的url、method
            _self.reqUrl=arguments[1];
            _self.reqMethod=arguments[0];
            // 在调用原生 open 实现重写
            _self.xhrOpen.apply(this,arguments);
        }

        // 重写 send
        XMLHttpRequest.prototype.send=function(){
            // 记录xhr
            varxhrmsg={
                'url': _self.reqUrl,
                'type': _self.reqMethod,
                // 此处可以取得 ajax 的请求参数
                'data': arguments[0]||{}
            }

            this.addEventListener('readystatechange',function(){
                if(this.readyState===4){
                    // 此处可以取得一些响应信息
                    // 响应信息
                    xhrmsg['res']=this.response;
                    xhrmsg['status']=this.status;
                    this.status>=200&&this.status<400 ?
                        xhrmsg['level']='success' : xhrmsg['level']='error';
                    xhrArray.push(xhrmsg);
                }
            });

            _self.xhrSend.apply(this,arguments);
        }
    }
```
##### axios举例：
以最常用的 HTTP 请求库 axios 为例，模拟接口响应 401 的情况：

```javascript
// 请求
axios.get(/api/test/401")
// 结果
Uncaught (in promise) Error: Request failed with status code 401
at createError (axios.js:1207)
at settle (axios.js:1177)
at XMLHttpRequest.handleLoad (axios.js:1037)
```
可以看出来 axios 的异常可以当做 Promise 异常来处理：

```javascript
// 请求
axios.get("http://localhost:3000/api/uitest/sentry/401")
.then(data => console.log('接口请求成功', data))
.catch(e => console.log('接口请求出错', e));
// 结果
接口请求出错 Error: Request failed with status code 401
at createError (createError.js:17)
at settle (settle.js:18)
at XMLHttpRequest.handleLoad (xhr.js:62)
```

一般接口 401 就代表用户未登录，就需要跳转到登录页，让用户进行重新登录，但如果每个请求方法都需要写一遍跳转登录页的逻辑就很麻烦了，这时候就会考虑使用 axios 的拦截器来做统一梳理，同理能统一处理的异常也可以在放在拦截器里处理。

```javascript
// Add a response interceptor
axios.interceptors.response.use(
  function (response) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
  },
  function (error) {
    if (error.response.status === 401) {
      goLogin(); // 跳转登录页
    } else if (error.response.status === 502) {
      alert(error.response.data.message || "系统升级中，请稍后重试");
    }
    return Promise.reject(error.response);
  }
);
```
#### 总结：

 - 可疑区域增加try-catch主动捕获异常。
 - 全局监控JS异常：window.onerror
 - 全局监听静态资源异常：window.addEventListener()
 - 捕获没有catch的Promise异常用unhandledrejection主动捕获异常。
 - Vue errorHandler和React componentDidCatch等MVVM框架的异常处理API
 - axios请求统一异常处理用拦截器interceptors
 - 使用日志监控服务收集用户错误信息

 #### 异常上报

即使前端开发完成后，会有一系列的 Web 应用的上线前的验证，如自测、QA 测试、code review 等，以确保应用能在生产上没有事故。

但是事与愿违，很多时候有一些问题，我们在测试中并未发现，可是在线上却有部分人出现了，问题确确实实存在的，这个时候我们测试环境又不能重现，还有一些偶现的生产的偶现问题，这些问题都很难定位到问题的原因，又不可能每次都远程给用户解决问题或者让用户按 F12 打开浏览器控制台把错误信息截图给我们吧。这时，我们不得不借助一些工具来解决这一系列令人头疼的问题。

前端错误监控日志系统就应用而生。当前端代码在生产运行中出现错误的时候，第一时间传递给监控系统，从而第一时间定位并且解决问题。

有很多成熟的方案可供选择： ARMS、fundebug、BadJS、Sentry。
也可以选择以下两种主流的错误上报方式：
   - 通过Ajax发送数据
   - 因为Ajax请求本身也有可能会发生异常，而且有可能会引发跨域问题，一般情况下更推荐使用动态创建img标签的形式进行上报。
   - 动态创建 img 标签的形式
   - new Image().src = reportUrl + '?msg=' + msg;
以Sentry为例，结合业务进行一些改造：
   - 与构建系统结合，构建项目时自动生成 Sentry 项目，注入 Sentry 脚本
   - 客服端注入 Sentry 客户端脚本后，按项目、页面等不同粒度配置告警事件的过滤规则
   - 对接消息系统，将告警消息推送到订阅群
   - 过滤接口错误和优化 Promise 错误上报信息

**Sentry监控原理简单分析：**
 - window.onerror
 每当代码在 runtime 时发生错误时，JavaScript 引擎就会抛出一个 Error 对象，并且触发 window.onerror 函数。

 ```javascript
    window.onerror = (msg, url, line, col, err) => {
    console.log(err)
    }
 ```
- unhandledrejection

在我们使用 Promise 的时候，如果发生错误而我们没有去 catch 的话，`window.onerror` 是不能监控到这个错误的。但是这个时候，JavaScript 引擎会触发 `unhandledrejection `事件，只要我们监听这个事件，那么就能够监控到 Promise 产生的错误。

```javascript
window.addEventListener('unhandledrejection', function(err) {
  console.log(err)
})
```

[JS错误收集及解决方案](/js_docs/JS错误收集及解决方案.md)

